export const SCRAPING_CONFIG = {
  maxPages: 5,
  pageTimeout: 30000,
  networkIdleTimeout: 8000, // Aguarda JS frameworks renderizarem (Angular/React)
  delayBetweenPages: 1000,

  removeSelectors: [
    'script',
    'style',
    'iframe',
    'noscript',
    '.cookie-banner',
    '.cookie-consent',
    '.popup',
    '.modal',
    '#chat-widget',
    '.chat-widget',
    '[role="dialog"]',
    'nav',
    'header',
    'footer',
  ],

  menuKeywords: {
    pt: [
      'sobre',
      'quem somos',
      'a empresa',
      'nossa história',
      'historia',
      'serviços',
      'servicos',
      'produtos',
      'portfolio',
      'portfólio',
      'galeria',
      'trabalhos',
      'projetos',
      'equipe',
      'time',
      'nosso time',
      'nossa equipe',
    ],
    en: [
      'about',
      'about us',
      'our story',
      'who we are',
      'services',
      'products',
      'properties',
      'portfolio',
      'gallery',
      'work',
      'projects',
      'team',
      'our team',
      'staff',
    ],
    es: [
      'sobre nosotros',
      'quienes somos',
      'servicios',
      'productos',
      'equipo',
      'nuestro equipo',
      'portfolio',
      'trabajos',
    ],
  },

  ignorePatterns: [
    '/contact',
    '/contato',
    '/contacto',
    '/privacy',
    '/privacidade',
    '/politica',
    '/terms',
    '/termos',
    '/legal',
    '/login',
    '/signin',
    '/signup',
    '/register',
    '/cadastro',
    '/cart',
    '/carrinho',
    '/checkout',
    '/blog',
    '/news',
    '/noticias',
    '#',
    'javascript:',
    'mailto:',
    'tel:',
    'sms:',
    'whatsapp:',
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'linkedin.com',
    'youtube.com',
    'tiktok.com',
    'pinterest.com',
    '.pdf',
    '.doc',
    '.docx',
    '.xls',
    '.xlsx',
    '.zip',
    '.rar',
  ],

  puppeteer: {
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--disable-gpu',
      '--window-size=1280,720',
      '--disable-web-security',
      '--disable-features=IsolateOrigins,site-per-process',
    ],
    defaultViewport: {
      width: 1280,
      height: 720,
    },
  },
};

export const SCRAPING_ERRORS = {
  CONNECTION_REFUSED: {
    code: 'ERR_CONNECTION_REFUSED',
    message: 'Site fora do ar ou inacessível',
    userMessage:
      'Não foi possível acessar o website. Verifique se está online.',
  },
  TIMEOUT: {
    code: 'ERR_TIMEOUT',
    message: 'Timeout ao acessar website',
    userMessage: 'O website demorou muito para responder.',
  },
  BLOCKED: {
    code: 'ERR_BLOCKED',
    message: 'Acesso bloqueado pelo website',
    userMessage:
      'O website bloqueou o acesso automático. Entre em contato com o suporte.',
  },
  INVALID_URL: {
    code: 'ERR_INVALID_URL',
    message: 'URL inválida',
    userMessage: 'O endereço do website não é válido.',
  },
  AI_PARSE_ERROR: {
    code: 'ERR_AI_PARSE',
    message: 'Erro ao estruturar dados com IA',
    userMessage: 'Erro ao processar conteúdo do website.',
  },
  NO_CONTENT: {
    code: 'ERR_NO_CONTENT',
    message: 'Nenhum conteúdo encontrado',
    userMessage: 'Não foi possível extrair informações do website.',
  },
  UNKNOWN: {
    code: 'ERR_UNKNOWN',
    message: 'Erro desconhecido',
    userMessage: 'Erro inesperado ao analisar website.',
  },
};
